const AUTH={issuer:"https://auth.pauhu.ai",authorize:"https://auth.pauhu.ai/authorize",token:"https://auth.pauhu.ai/token",client_id:"pauhu-demo-web",redirect_uri:window.location.origin+"/haminanenergia/",scope:"openid profile offline_access api.read"};
function b64url(a){return btoa(String.fromCharCode.apply(null,new Uint8Array(a))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function sha256(t){const d=new TextEncoder().encode(t);const h=await crypto.subtle.digest('SHA-256',d);return new Uint8Array(h);}
async function pkce(){const v=[...crypto.getRandomValues(new Uint8Array(32))].map(b=>('0'+b.toString(16)).slice(-2)).join('');const c=b64url(await sha256(v));const s=crypto.getRandomValues(new Uint32Array(1))[0].toString(16);sessionStorage.setItem('pkce_verifier',v);sessionStorage.setItem('oauth_state',s);return{v,c,s};}
function getToken(){return sessionStorage.getItem('access_token')||"";}
function clearTokens(){['access_token','id_token','refresh_token','expires_at'].forEach(k=>sessionStorage.removeItem(k));}
async function beginLogin(){const {v,c,s}=await pkce();const u=new URL(AUTH.authorize);u.searchParams.set('client_id',AUTH.client_id);u.searchParams.set('response_type','code');u.searchParams.set('redirect_uri',AUTH.redirect_uri);u.searchParams.set('scope',AUTH.scope);u.searchParams.set('code_challenge',c);u.searchParams.set('code_challenge_method','S256');u.searchParams.set('state',s);window.location.assign(u.toString());}
async function handleRedirect(){const p=new URLSearchParams(window.location.search);const code=p.get('code');const st=p.get('state');if(!code)return false;const exp=sessionStorage.getItem('oauth_state');if(exp&&st!==exp){console.warn('state mismatch');return false;}const body=new URLSearchParams();body.set('grant_type','authorization_code');body.set('client_id',AUTH.client_id);body.set('redirect_uri',AUTH.redirect_uri);body.set('code_verifier',sessionStorage.getItem('pkce_verifier')||'');body.set('code',code);const r=await fetch(AUTH.token,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const j=await r.json();if(j.access_token){sessionStorage.setItem('access_token',j.access_token);if(j.id_token)sessionStorage.setItem('id_token',j.id_token);if(j.refresh_token)sessionStorage.setItem('refresh_token',j.refresh_token);if(j.expires_in)sessionStorage.setItem('expires_at',(Date.now()+j.expires_in*1000).toString());history.replaceState({},document.title,window.location.pathname);return true;}return false;}
async function logout(){clearTokens();}
window.AUTH_BRIDGE={beginLogin,handleRedirect,getToken,logout};
